### ISSUE TITLE
Scaling logs

### ISSUE THREAD

**Issue by kpena027** [aws-samples/amazon-ecs-stopped-tasks-cwlogs#2]
It would be beneficial to also add support to log ECS scaling events. A separate log group and event could be configured to add this functionality. Would it make sense to add this into this repo, as the repo name references stopped tasks?

**Comment by fjromerom** [comment]
The current EventBridge event pattern accepts any stopped task, no matter what triggered it. Thus, tasks that are stopped by scaling activities will be also logged. If you wish to log ECS service events then that's a different story out of the scope of this project.
